### ISSUE TITLE
Help to run

### ISSUE THREAD

**Issue by vatsal-26** [arafaysaleem/library_management_system#2]
please help me to run this project i am finding issues in running!

**Comment by arafaysaleem** [comment]
what issues are you having?

**Comment by vatsal-26** [comment]
When u scan the Barcode...there is no book in the inventory page

**Comment by vatsal-26** [comment]
When i**

Please help me

**Comment by vatsal-26** [comment]
Actually, when u unzip the file...I don't see the code running I get errors

**Comment by vatsal-26** [comment]
Is it possible to come on team viewer u solving the error and help to run
the app? Please

**Comment by vatsal-26** [comment]
Hey??

**Comment by arafaysaleem** [comment]
Since the flutter API has changed alot than at the time of the project, it's going to take significant effort to migrate it, especially with null safety.

**Comment by arafaysaleem** [comment]
Also, the errors arising are in your own custom implementation and not related to this project's original code so I'm going to close this issue.
